version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: aiherobattle
      POSTGRES_USER: aihero
      POSTGRES_PASSWORD: aiheropass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: ./backend
    command: sh -c "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run start -- --host 0.0.0.0"
    depends_on:
      - web
  redis:
    image: redis:7
    ports:
      - "6380:6379"
  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
volumes:
  postgres_data: 