version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: aiherobattle
      POSTGRES_USER: aihero
      POSTGRES_PASSWORD: aiheropass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c "echo 'Waiting for database...' && echo 'Database started.' && echo 'Starting migrations...' && python manage.py migrate && echo 'Collecting static files...' && python manage.py collectstatic --noinput && if [ \"$$USE_GUNICORN\" = \"True\" ]; then echo 'Starting Gunicorn...' && gunicorn backend.wsgi:application --bind 0.0.0.0:8000; else echo 'Starting Django development server...' && python manage.py runserver 0.0.0.0:8000; fi"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  redis:
    image: redis:7
    ports:
      - "6380:6379"
  celery:
    build: .
    command: celery -A backend worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A backend beat -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
volumes:
  postgres_data: 