# Generated by Django 5.0.2 on 2025-06-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='battle',
            name='battle_log',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_won', to='game.character'),
        ),
    ]
