# Generated by Django 5.0.2 on 2025-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_battle_options_alter_battle_battle_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PENDING', max_length=10),
        ),
    ]
