# Generated by Django 5.0.2 on 2025-06-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_battle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='game.character'),
        ),
    ]
