# Generated by Django 5.0.2 on 2025-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_battle_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
    ]
