# Generated by Django 5.0.2 on 2025-06-24 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_character_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='diamond',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='last_energy_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='max_energy',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='prompt_power',
            field=models.IntegerField(default=5),
        ),
    ]
