# Generated by Django 5.0.2 on 2025-06-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_diamond_player_energy_player_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chain_id',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='player',
            name='login_method',
            field=models.CharField(choices=[('google', 'Google OAuth'), ('metamask', 'MetaMask'), ('walletconnect', 'WalletConnect'), ('coinbase', 'Coinbase Wallet'), ('email', 'Email Wallet'), ('phone', 'Phone Wallet'), ('social', 'Social Login')], default='google', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='social_provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='thirdweb_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
