# Generated by Django 5.0.2 on 2025-06-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_chain_id_player_login_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.IntegerField(choices=[(1, 'N - Normal'), (2, 'R - Rare'), (3, 'SR - Super Rare'), (4, 'SSR - Super Super Rare'), (5, 'UR - Ultra Rare')], default=1),
        ),
    ]
