# Generated by Django 5.0.2 on 2025-06-26 09:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_character_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='任務名稱')),
                ('description', models.TextField(verbose_name='任務描述')),
                ('quest_type', models.CharField(choices=[('daily_checkin', '每日簽到'), ('battle_count', '對戰次數'), ('battle_win', '對戰勝利'), ('character_summon', '召喚角色'), ('login_streak', '連續登入')], max_length=20, verbose_name='任務類型')),
                ('target_count', models.IntegerField(default=1, verbose_name='目標數量')),
                ('reward_gold', models.IntegerField(default=0, verbose_name='金幣獎勵')),
                ('reward_diamond', models.IntegerField(default=0, verbose_name='鑽石獎勵')),
                ('reward_prompt_power', models.IntegerField(default=0, verbose_name='Prompt Power獎勵')),
                ('reward_energy', models.IntegerField(default=0, verbose_name='體力獎勵')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '每日任務',
                'verbose_name_plural': '每日任務',
            },
        ),
        migrations.CreateModel(
            name='PlayerDailyQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_count', models.IntegerField(default=0, verbose_name='當前進度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='是否領取獎勵')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='任務日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='領取時間')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to='game.player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.dailyquest')),
            ],
            options={
                'verbose_name': '玩家每日任務',
                'verbose_name_plural': '玩家每日任務',
                'unique_together': {('player', 'quest', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlayerLoginRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to='game.player')),
            ],
            options={
                'verbose_name': '玩家登入記錄',
                'verbose_name_plural': '玩家登入記錄',
                'unique_together': {('player', 'login_date')},
            },
        ),
    ]
