# Generated by Django 5.0.2 on 2025-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_dailyquest_playerdailyquest_playerloginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='暱稱'),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname_changed',
            field=models.BooleanField(default=False, verbose_name='是否已改過暱稱'),
        ),
    ]
