# Generated by Django 5.0.2 on 2025-06-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_nickname_player_nickname_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquest',
            name='reward_diamond',
        ),
        migrations.RemoveField(
            model_name='player',
            name='diamond',
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='目前經驗值'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_minted',
            field=models.BooleanField(default=False, verbose_name='是否已鑄造為 NFT'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='等級'),
        ),
        migrations.AddField(
            model_name='character',
            name='nft_token_id',
            field=models.PositiveIntegerField(blank=True, help_text='NFT 的 Token ID', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='nft_transaction_hash',
            field=models.CharField(blank=True, help_text='鑄造交易的雜湊值', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='reward_exp_potion',
            field=models.IntegerField(default=0, verbose_name='經驗藥水獎勵'),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='reward_prompt',
            field=models.IntegerField(default=0, verbose_name='$PROMPT 代幣獎勵'),
        ),
        migrations.AddField(
            model_name='player',
            name='exp_potion',
            field=models.PositiveIntegerField(default=100, verbose_name='經驗藥水'),
        ),
        migrations.AddField(
            model_name='player',
            name='prompt',
            field=models.PositiveIntegerField(default=10, verbose_name='$PROMPT 代幣'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gold',
            field=models.PositiveIntegerField(default=1000, verbose_name='金幣'),
        ),
        migrations.AlterField(
            model_name='player',
            name='prompt_power',
            field=models.PositiveIntegerField(default=5, verbose_name='Prompt Power'),
        ),
    ]
