# Generated by Django 5.0.2 on 2025-08-15 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_dailyquest_reward_diamond_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='賽季名稱')),
                ('start_date', models.DateTimeField(verbose_name='開始時間')),
                ('end_date', models.DateTimeField(verbose_name='結束時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('prize_pool', models.PositiveIntegerField(default=0, verbose_name='獎金池')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '天梯賽季',
                'verbose_name_plural': '天梯賽季',
            },
        ),
        migrations.CreateModel(
            name='BettingStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_bets', models.PositiveIntegerField(default=0, verbose_name='總下注次數')),
                ('total_bet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總下注金額')),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總獲利')),
                ('win_count', models.PositiveIntegerField(default=0, verbose_name='獲勝次數')),
                ('current_streak', models.IntegerField(default=0, verbose_name='當前連勝')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='最佳連勝')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='betting_stats', to='game.player')),
            ],
            options={
                'verbose_name': '下注統計',
                'verbose_name_plural': '下注統計',
            },
        ),
        migrations.CreateModel(
            name='LadderRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_points', models.IntegerField(default=1000, verbose_name='排名積分')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='勝場')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='敗場')),
                ('current_rank', models.PositiveIntegerField(default=999999, verbose_name='當前排名')),
                ('is_eligible', models.BooleanField(default=True, verbose_name='是否有參戰資格')),
                ('last_battle_at', models.DateTimeField(blank=True, null=True, verbose_name='最後參戰時間')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_ranks', to='game.character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_ranks', to='game.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='game.ladderseason')),
            ],
            options={
                'verbose_name': '天梯排名',
                'verbose_name_plural': '天梯排名',
                'ordering': ['current_rank'],
                'unique_together': {('season', 'player', 'character')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledBattle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(verbose_name='預定戰鬥時間')),
                ('betting_start_time', models.DateTimeField(verbose_name='下注開始時間')),
                ('betting_end_time', models.DateTimeField(verbose_name='下注截止時間')),
                ('status', models.CharField(choices=[('scheduled', '已排程'), ('betting_open', '開放下注'), ('betting_closed', '下注截止'), ('in_progress', '戰鬥中'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20)),
                ('total_bets_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總下注金額')),
                ('fighter1_bets_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='選手1下注金額')),
                ('fighter2_bets_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='選手2下注金額')),
                ('fighter1_odds', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='選手1賠率')),
                ('fighter2_odds', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='選手2賠率')),
                ('battle_log', models.JSONField(blank=True, null=True, verbose_name='戰鬥記錄')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fighter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_fighter1', to='game.ladderrank')),
                ('fighter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_fighter2', to='game.ladderrank')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='game.ladderseason')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='game.ladderrank', verbose_name='勝利者')),
            ],
            options={
                'verbose_name': '定時戰鬥',
                'verbose_name_plural': '定時戰鬥',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='BattleBet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='下注金額')),
                ('odds_at_bet', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='下注時賠率')),
                ('is_winner', models.BooleanField(blank=True, null=True, verbose_name='是否獲勝')),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='獲利金額')),
                ('is_settled', models.BooleanField(default=False, verbose_name='是否已結算')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='結算時間')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_bets', to='game.player')),
                ('chosen_fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ladderrank', verbose_name='選擇的選手')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.scheduledbattle')),
            ],
            options={
                'verbose_name': '下注記錄',
                'verbose_name_plural': '下注記錄',
                'unique_together': {('battle', 'player')},
            },
        ),
    ]
