# Generated by Django 5.0.2 on 2025-10-23 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_ladderseason_bettingstats_ladderrank_scheduledbattle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='節點名稱')),
                ('url', models.URLField(verbose_name='節點API地址')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API密鑰')),
                ('status', models.CharField(choices=[('online', '在線'), ('offline', '離線'), ('error', '錯誤'), ('maintenance', '維護中')], default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最後心跳時間')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='總請求數')),
                ('successful_requests', models.PositiveIntegerField(default=0, verbose_name='成功請求數')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均響應時間(秒)')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='權重')),
                ('max_concurrent_requests', models.PositiveIntegerField(default=5, verbose_name='最大並發請求數')),
                ('current_requests', models.PositiveIntegerField(default=0, verbose_name='當前請求數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI節點',
                'verbose_name_plural': 'AI節點',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleVotingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_winner_id', models.CharField(max_length=100, verbose_name='投票的獲勝者ID')),
                ('battle_result', models.JSONField(verbose_name='節點返回的戰鬥結果')),
                ('response_time', models.FloatField(verbose_name='響應時間(秒)')),
                ('is_valid', models.BooleanField(default=True, verbose_name='投票是否有效')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='錯誤信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_records', to='game.battle')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.ainode')),
            ],
            options={
                'verbose_name': '戰鬥投票記錄',
                'verbose_name_plural': '戰鬥投票記錄',
                'unique_together': {('battle', 'node')},
            },
        ),
    ]
