# Generated by Django 5.0.2 on 2025-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_ainode_battlevotingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='合約地址'),
        ),
        migrations.AddField(
            model_name='character',
            name='minted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='鑄造時間'),
        ),
        migrations.AddField(
            model_name='character',
            name='owner_wallet',
            field=models.CharField(blank=True, db_index=True, max_length=42, null=True, verbose_name='持有者錢包'),
        ),
        migrations.AddField(
            model_name='character',
            name='token_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='NFT Token ID'),
        ),
        migrations.AddField(
            model_name='character',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True, verbose_name='交易哈希'),
        ),
        migrations.AlterField(
            model_name='character',
            name='nft_token_id',
            field=models.PositiveIntegerField(blank=True, help_text='NFT 的 Token ID (deprecated)', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='nft_transaction_hash',
            field=models.CharField(blank=True, help_text='鑄造交易的雜湊值 (deprecated)', max_length=255, null=True),
        ),
    ]
