# Generated by Django 5.0.2 on 2025-11-03 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_battle_onchain_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='鏈上 Listing ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='價格')),
                ('currency', models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42, verbose_name='支付代幣地址')),
                ('status', models.CharField(choices=[('active', '上架中'), ('sold', '已售出'), ('cancelled', '已取消'), ('expired', '已過期')], default='active', max_length=20)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='上架交易哈希')),
                ('cancel_tx_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='取消交易哈希')),
                ('buy_tx_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='購買交易哈希')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='game.player')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='game.character')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='game.player')),
            ],
            options={
                'verbose_name': '角色上架',
                'verbose_name_plural': '角色上架',
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='交易價格')),
                ('currency', models.CharField(max_length=42, verbose_name='支付代幣地址')),
                ('tx_hash', models.CharField(max_length=66, unique=True, verbose_name='交易哈希')),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_transactions', to='game.player')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_transactions', to='game.character')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='game.characterlisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_transactions', to='game.player')),
            ],
            options={
                'verbose_name': '市場交易',
                'verbose_name_plural': '市場交易',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='價格')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='game.character')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.markettransaction')),
            ],
            options={
                'verbose_name': '價格歷史',
                'verbose_name_plural': '價格歷史',
                'ordering': ['-timestamp'],
            },
        ),
    ]
