# Generated by Django 5.0.2 on 2025-11-04 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_characterlisting_markettransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterlisting',
            name='currency',
            field=models.CharField(default='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', max_length=42, verbose_name='支付代幣地址'),
        ),
        migrations.CreateModel(
            name='DailyMNTDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=42, verbose_name='錢包地址')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='發放金額（MNT）')),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='交易哈希')),
                ('distribution_date', models.DateField(default=django.utils.timezone.now, verbose_name='發放日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnt_distributions', to='game.player')),
            ],
            options={
                'verbose_name': '每日 MNT 發放記錄',
                'verbose_name_plural': '每日 MNT 發放記錄',
                'indexes': [models.Index(fields=['player', 'distribution_date'], name='game_dailym_player__33ba3d_idx')],
                'unique_together': {('player', 'distribution_date')},
            },
        ),
    ]
